# Day 1: Tensors in Machine Learning

Tensors are the fundamental building blocks in many machine learning libraries like TensorFlow and PyTorch. They're essentially multi-dimensional arrays, and understanding them lays the groundwork for understanding how data flows through neural networks.

---

### First import the numpy library

In [2]:
import numpy as np

### 0-D Tensors (Scalars)

In [28]:
a = np.array(5)
print(a)
print(f"Dimension: {a.ndim}")
print(f"Shape: {a.shape}")

5
Dimension: 0
Shape: ()


A scalar has no axis — it's just a single number.

### 1-D Tensors (Vectors)

In [44]:
b = np.array([3, 7, 9])
print(b)
print("Dimension: {b.ndim}")
print(f"Shape: {b.shape}")

[3 7 9]

Dimension: {b.ndim}
Shape: (3,)


Vectors are 1D arrays. They're often used to represent features or weights in ML.

### 2-D Tensors (Matrices)

In [45]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(f"Dimension: {c.ndim}")
print(f"Shape: {c.shape}")

[[1 2 3]
 [4 5 6]]
Dimension: 2
Shape: (2, 3)


Matrices (2D tensors) are used in data tables, grayscale images, and weight matrices.

### 3-D Tensors

In [46]:
d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(d)
print(f"Dimension: {d.ndim}")
print(f"Shape: {d.shape}")

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Dimension: 3
Shape: (2, 2, 2)


Think of this as a stack of matrices. Commonly used in colored image data:

- RGB images: `(height, width, 3 channels)`

### 4-D Tensors

In [32]:
e = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]],
              [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print(e)
print(f"Dimension: {e.ndim}")
print(f"Shape: {e.shape}")

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
Dimension: 4
Shape: (2, 2, 2, 2)


Used for batches of RGB images:

- `(batch_size, height, width, channels)`

### 5️⃣–7️⃣ N-D Tensors
Continue the pattern...

In [ ]:
f = np.array([...])  # 5D
g = np.array([...])  # 6D
h = np.array([...])  # 7D

# Print their ndim and shape similarly

The deeper you go, the more abstract — used in NLP, video data, volumetric scans, etc.

### 5-D Tensors

In [47]:
f = np.array([
    [
        [ [[1, 2], [3, 4]], [[5, 6], [7, 8]] ],
        [ [[9, 10], [11, 12]], [[13, 14], [15, 16]] ]
    ],
    [
        [ [[17, 18], [19, 20]], [[21, 22], [23, 24]] ],
        [ [[25, 26], [27, 28]], [[29, 30], [31, 32]] ]
    ]
])
print(f)
print(f"Dimension: {f.ndim}")
print(f"Shape: {f.shape}")

[[[[[ 1  2]
    [ 3  4]]

   [[ 5  6]
    [ 7  8]]]


  [[[ 9 10]
    [11 12]]

   [[13 14]
    [15 16]]]]



 [[[[17 18]
    [19 20]]

   [[21 22]
    [23 24]]]


  [[[25 26]
    [27 28]]

   [[29 30]
    [31 32]]]]]
Dimension: 5
Shape: (2, 2, 2, 2, 2)


#### Interpretation:
This 5D tensor can be interpreted as:

**(batch_size=2, time=2, height=2, width=2, channels=2)**

#### Real-world usage:

- Video classification with grayscale images over time.
- 3D volumetric data (like CT scans) where depth adds another dimension.

### 6-D Tensors

In [48]:
g = np.array([
    [
        [
            [[ [1, 2], [3, 4] ], [ [5, 6], [7, 8] ]],
            [[ [9, 10], [11, 12] ], [ [13, 14], [15, 16] ]]
        ],
        [
            [[ [17, 18], [19, 20] ], [ [21, 22], [23, 24] ]],
            [[ [25, 26], [27, 28] ], [ [29, 30], [31, 32] ]]
        ]
    ],
    [
        [
            [[ [1, 2], [3, 4] ], [ [5, 6], [7, 8] ]],
            [[ [9, 10], [11, 12] ], [ [13, 14], [15, 16] ]]
        ],
        [
            [[ [17, 18], [19, 20] ], [ [21, 22], [23, 24] ]],
            [[ [25, 26], [27, 28] ], [ [29, 30], [31, 32] ]]
        ]
    ]
])
print(g)
print(f"Dimension: {g.ndim}")
print(f"Shape: {g.shape}")

[[[[[[ 1  2]
     [ 3  4]]

    [[ 5  6]
     [ 7  8]]]


   [[[ 9 10]
     [11 12]]

    [[13 14]
     [15 16]]]]



  [[[[17 18]
     [19 20]]

    [[21 22]
     [23 24]]]


   [[[25 26]
     [27 28]]

    [[29 30]
     [31 32]]]]]




 [[[[[ 1  2]
     [ 3  4]]

    [[ 5  6]
     [ 7  8]]]


   [[[ 9 10]
     [11 12]]

    [[13 14]
     [15 16]]]]



  [[[[17 18]
     [19 20]]

    [[21 22]
     [23 24]]]


   [[[25 26]
     [27 28]]

    [[29 30]
     [31 32]]]]]]
Dimension: 6
Shape: (2, 2, 2, 2, 2, 2)


#### Interpretation:

(batch_size=2, video_frames=2, time_steps=2, height=2, width=2, channels=2)

#### Real-world usage:

- Multi-camera video processing
- Time-series of 3D volumes
- Batch of MRI scans over time

### 7-D Tensors

In [54]:
h = np.array([
    [
    [  # 1st group
        [  # 1st sub-group
            [  # 1st block
                [[1, 2], [3, 4]],
                [[5, 6], [7, 8]]
            ],
            [
                [[9, 10], [11, 12]],
                [[13, 14], [15, 16]]
            ]
        ],
        [
            [  # 2nd block
                [[17, 18], [19, 20]],
                [[21, 22], [23, 24]]
            ],
            [
                [[25, 26], [27, 28]],
                [[29, 30], [31, 32]]
            ]
        ]
    ],
    [  # 2nd group
        [  # 1st sub-group
            [
                [[1, 2], [3, 4]],
                [[5, 6], [7, 8]]
            ],
            [
                [[9, 10], [11, 12]],
                [[13, 14], [15, 16]]
            ]
        ],
        [
            [
                [[17, 18], [19, 20]],
                [[21, 22], [23, 24]]
            ],
            [
                [[25, 26], [27, 28]],
                [[29, 30], [31, 32]]
            ]
        ]
    ],
    [  # 3rd group
        [
            [
                [[1, 2], [3, 4]],
                [[5, 6], [7, 8]]
            ],
            [
                [[9, 10], [11, 12]],
                [[13, 14], [15, 16]]
            ]
        ],
        [
            [
                [[17, 18], [19, 20]],
                [[21, 22], [23, 24]]
            ],
            [
                [[25, 26], [27, 28]],
                [[29, 30], [31, 32]]
            ]
        ]
    ],
    [  # 4th group
        [
            [
                [[1, 2], [3, 4]],
                [[5, 6], [7, 8]]
            ],
            [
                [[9, 10], [11, 12]],
                [[13, 14], [15, 16]]
            ]
        ],
        [
            [
                [[17, 18], [19, 20]],
                [[21, 22], [23, 24]]
            ],
            [
                [[25, 26], [27, 28]],
                [[29, 30], [31, 32]]
            ]
        ]
    ]
    ]    
])
print(h)
print("\nShape:", h.shape)  # (1, 4, 2, 2, 2, 2, 2)
print("Dimensions:", h.ndim)  # 7

[[[[[[[ 1  2]
      [ 3  4]]

     [[ 5  6]
      [ 7  8]]]


    [[[ 9 10]
      [11 12]]

     [[13 14]
      [15 16]]]]



   [[[[17 18]
      [19 20]]

     [[21 22]
      [23 24]]]


    [[[25 26]
      [27 28]]

     [[29 30]
      [31 32]]]]]




  [[[[[ 1  2]
      [ 3  4]]

     [[ 5  6]
      [ 7  8]]]


    [[[ 9 10]
      [11 12]]

     [[13 14]
      [15 16]]]]



   [[[[17 18]
      [19 20]]

     [[21 22]
      [23 24]]]


    [[[25 26]
      [27 28]]

     [[29 30]
      [31 32]]]]]




  [[[[[ 1  2]
      [ 3  4]]

     [[ 5  6]
      [ 7  8]]]


    [[[ 9 10]
      [11 12]]

     [[13 14]
      [15 16]]]]



   [[[[17 18]
      [19 20]]

     [[21 22]
      [23 24]]]


    [[[25 26]
      [27 28]]

     [[29 30]
      [31 32]]]]]




  [[[[[ 1  2]
      [ 3  4]]

     [[ 5  6]
      [ 7  8]]]


    [[[ 9 10]
      [11 12]]

     [[13 14]
      [15 16]]]]



   [[[[17 18]
      [19 20]]

     [[21 22]
      [23 24]]]


    [[[25 26]
      [27 28]]

     [[29 30]
      

#### Interpretation:

A hypothetical use case in deep learning for complex structured datasets like:
- `(batch, group, time, camera, height, width, channels)`
- Advanced recurrent spatio-temporal models in research

#### Real-world usage:

Rare in practice, but possible in:
- Deep video understanding
-Scientific simulations with nested dimensions
- Tensor decomposition and multimodal learning (vision + audio + temporal)

### Key Takeaways

| Tensor Dim | Meaning                         | Example Use                              |
| ---------- | ------------------------------- | ---------------------------------------- |
| 0-D        | Scalar                          | Single value                             |
| 1-D        | Vector                          | Feature vector                           |
| 2-D        | Matrix                          | Grayscale image, weight matrices         |
| 3-D        | Stack of matrices               | RGB image, word embeddings               |
| 4-D        | Batch of images                 | CNN inputs                               |
| 5-D        | Batch of image sequences        | Videos, 3D data                          |
| 6-D        | Sequences of volumetric data    | Medical imaging time-series              |
| 7-D        | Complex nested sequence/volumes | Multimodal AI models, rare scientific ML |