# What is a Tensor?
A tensor ia a generalization of scalars, vectors, and matrices to higher dimensions. It's just a container for numbers(data), and it can be of any number of dimensions(called rank).

| Tensor Type | Example Shape    | What It Represents                        |
| ----------- | ---------------- | ----------------------------------------- |
| Scalar      | `()`             | Single number (0D tensor)                 |
| Vector      | `(n,)`           | 1D array (1D tensor)                      |
| Matrix      | `(m, n)`         | 2D array (2D tensor)                      |
| 3D Tensor   | `(d, m, n)`      | e.g. Image data (channels, height, width) |
| nD Tensor   | `(a, b, ..., z)` | Any number of dimensions                  |


## Why use Tensors in ML?
- They allow for efficient representation of data (images, sequences, etc.)
- Support for batch processing (eg. `batch_size x height x width x channels`)
- GPU Accleration (especially with Tensorflow.PyTorch)
- Great for linear algebra operations (which ML models use heavily)

## Tensors in NumPy 

### 0D Tensor - Scalar

In [1]:
import numpy as np

In [6]:
scalar = np.array(34)
print("0D tensor (scalar):", scalar)
print("Shape:", scalar.shape)
print("Dimensions:", scalar.ndim)

0D tensor (scalar): 34
Shape: ()
Dimensions: 0


### 1D Tensor - Vector

In [9]:
vector = np.array([1, 2, 3])
print("1D tensor (vector):", vector)
print("Shape:", vector.shape)
print("Dimension:", vector.ndim)

1D tensor (vector): [1 2 3]
Shape: (3,)
Dimension: 1


### 2D Tensor - Matrix

In [14]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Tensor (matrix):")
print(matrix)
print("shape:", matrix.shape)
print("Dimension:", matrix.ndim)

2D Tensor (matrix):
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
Dimension: 2


### 3D Tensor - For example: RGB Image (Channels x Height x Width)

In [21]:
tensor3d = np.array([
    [[1, 2, 3], [4, 5, 6]], 
    [[11, 12, 13], [14, 15, 16]]
])
print("3D Tensor:")
print(tensor3d)
print("Dimension:", tensor3d.ndim)

3D Tensor:
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]
Dimension: 3


## Tensor Operations in NumPy

### 1. Reshaping